fix yamllint

diff --git a/.github/workflows/ci_checks.yaml b/.github/workflows/ci_checks.yaml
--- a/.github/workflows/ci_checks.yaml
+++ b/.github/workflows/ci_checks.yaml
@@ -19,11 +19,11 @@ jobs:
 
       - name: Run yamlint check
         run: |
-         pip install yamllint
-         (find . -name "*.yaml" -exec yamllint -c .yamllint {} \; || true) | tee -a tmp_yamllint.log
+         pip install yamllint > /dev/null 2>&1
+         find . -name "*.yaml" -exec yamllint -c .yamllint {} \; | tee -a tmp_yamllint.log
          error_warning_count=$(grep -c -E "error|warning" tmp_yamllint.log)
          if [[ $error_warning_count -gt 0 ]]; then
-          echo "$error_warning_count YAML linting errors or warnings found in tmp_yamllint.log"
+          echo "$error_warning_count YAML linting errors or warnings found in tmp_yamllint.log" || true
           exit 1
          fi
 
