fix yamllint

diff --git a/.github/workflows/ci_checks.yaml b/.github/workflows/ci_checks.yaml
--- a/.github/workflows/ci_checks.yaml
+++ b/.github/workflows/ci_checks.yaml
@@ -10,50 +10,50 @@ jobs:
   checks:
     runs-on: ubuntu-latest
 
-  steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up Terraform
-      uses: hashicorp/setup-terraform@v1
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v1
 
-    - name: Run yamlint check
-      run: |
-        pip install yamllint > /dev/null 2>&1
-        find . -name "*.yaml" -exec yamllint -c .yamllint {} \; | tee -a tmp_yamllint.log
-        error_warning_count=$(grep -c -E "error|warning" tmp_yamllint.log)
-        if [[ $error_warning_count -gt 0 ]]; then
-         echo "$error_warning_count YAML linting errors or warnings found in tmp_yamllint.log"
-         exit 1
-        fi
+      - name: Run yamlint check
+        run: |
+         pip install yamllint > /dev/null 2>&1
+         find . -name "*.yaml" -exec yamllint -c .yamllint {} \; | tee -a tmp_yamllint.log
+         error_warning_count=$(grep -c -E "error|warning" tmp_yamllint.log)
+         if [[ $error_warning_count -gt 0 ]]; then
+          echo "$error_warning_count YAML linting errors or warnings found in tmp_yamllint.log"
+          exit 1
+         fi
 
-    - name: Run JSON Validator check
-      run: |
-        find . -name "*.json" -exec python3 json_validator.py {} +
+      - name: Run JSON Validator check
+        run: |
+         find . -name "*.json" -exec python3 json_validator.py {} +
 
-    - name: Run tflint check
-      run: |
-        wget https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip > /dev/null 2>&1
-        unzip tflint_linux_amd64.zip > /dev/null 2>&1
-        sudo mv tflint /usr/local/bin/ > /dev/null 2>&1
-        tflint -f compact --recursive --only=terraform_unused_declarations
+      - name: Run tflint check
+        run: |
+         wget https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip > /dev/null 2>&1
+         unzip tflint_linux_amd64.zip > /dev/null 2>&1
+         sudo mv tflint /usr/local/bin/ > /dev/null 2>&1
+         tflint -f compact --recursive --only=terraform_unused_declarations
 
-    - name: Run Heredoc check
-      run: |
-        find . -type f -name "*.tf" -exec grep -H "<<" {} \; | tee -a tmp_heredoc.log
-        line_count=$(wc -l < tmp_heredoc.log | awk '{print $1}')
-        if [[ $line_count -gt 0 ]]; then
-         echo "$line_count lines in tmp_heredoc.log"
-         exit 1
-        fi
+      - name: Run Heredoc check
+        run: |
+         find . -type f -name "*.tf" -exec grep -H "<<" {} \; | tee -a tmp_heredoc.log
+         line_count=$(wc -l < tmp_heredoc.log | awk '{print $1}')
+         if [[ $line_count -gt 0 ]]; then
+          echo "$line_count lines in tmp_heredoc.log"
+          exit 1
+         fi
 
-    - name: Run Terraform fmt check
-      run: |
-        terraform fmt -check --recursive
+      - name: Run Terraform fmt check
+        run: |
+         terraform fmt -check --recursive
 
-    - name: Run tfsec check
-      run: |
-        wget https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64 > /dev/null 2>&1
-        chmod +x tfsec-linux-amd64 > /dev/null 2>&1
-        sudo mv tfsec-linux-amd64 /usr/local/bin/tfsec > /dev/null 2>&1
-        tfsec --no-color --minimum-severity MEDIUM --force-all-dirs || true
+      - name: Run tfsec check
+        run: |
+         wget https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64 > /dev/null 2>&1
+         chmod +x tfsec-linux-amd64 > /dev/null 2>&1
+         sudo mv tfsec-linux-amd64 /usr/local/bin/tfsec > /dev/null 2>&1
+         tfsec --no-color --minimum-severity MEDIUM --force-all-dirs || true
